version: "3.8"

services:
  redis:
    image: redis
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: django_app
    command: daphne -b 0.0.0.0 -p 8000 django_channels.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis